import { Geist, Geist_Mono, Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/test1_2/Header";
import SideBar from "@/components/test1_2/SideBar";

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });
export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<body
				suppressHydrationWarning
				className={`${inter.className} antialiased flex flex-col relative`}
			>
				<Header />
				<SideBar />
				{children}
			</body>
		</html>
	);
}
